version: '3'

services:
  go-server:
    image: go-server
    ports:
      - "3000:3000"
    depends_on:
      - redis-stack
    environment:
      JWTSECRET: "AkashJWT"
      PORT: 3000
      RAILS_DATABASE_HOST: "tiny.db.elephantsql.com"
      RAILS_DATABASE_NAME: "zmceklfm"
      RAILS_DATABASE_PASSWORD: "qkJLLuSNh4907i00-c_8NAdeZjLiRz4_"
      RAILS_DATABASE_PORT: "5432"
      RAILS_DATABASE_USER: "zmceklfm"

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
